### ISSUE TITLE
Не обновляется иконка лайков после нажатия

### ISSUE THREAD

**Issue by BorsukVV** [BorsukVV/NMedia#3]
# Описание проблемы

#### Шаги по воспроизведению

1. Открыть страницу отображения постов
2. Кликнуть иконку лайка (сердечко)

#### Ожидаемый результат

Иконка меняет свое отображение в соответствии с состоянием (лайкнуто/не_лайкнуто), счетчик лайков изменяет свое значение.

#### Фактический результат

Иконка и счетчик не изменяются после нажатия. Отрисовка происходит, если промотать список до конца и вернуться к началу списка.
При попытке использования строковых ресурсов в формате: 

`Resources.getSystem()
                            .getString(R.string.formatted_like_rep_view_count_without_suffix)`

Приложение компилируется, запускается в эмуляторе, но аварийно завершается при переходе к странице ленты постов

> E/netology.nmedi: No package ID 7f found for ID 0x7f0e002b.
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.netology.nmedia, PID: 6819
    android.content.res.Resources$NotFoundException: String resource ID #0x7f0e002b
        at android.content.res.Resources.getText(Resources.java:444)
        at android.content.res.Resources.getString(Resources.java:537)
        at ru.netology.nmedia.data.impl.PostsAdapter$ViewHolder.countFormatter(PostsAdapter.kt:57)

#### Программное окружение

* Windows 10
* Android Studio 2020.3.1 Patch 3

**Comment by BorsukVV** [comment]
Проблема с ресурсами решена:
в классе PostListItemActivity получаем ресурсы, затем передаем в PostAdapter

`        val templateNoSuf = resources.getString(R.string.formatted_like_rep_view_count_without_suffix)
        val templateOneDigSuf = resources.getString(R.string.formatted_like_rep_view_thousands_one_dig_suf)
        val templateTwoDigSuf = resources.getString(R.string.formatted_like_rep_view_count_two_dig_suf)
        val suffixThousands = resources.getString(R.string.suffix_thousands)
        val suffixMillions = resources.getString(R.string.suffix_millions)

        val adapter = PostsAdapter(
            viewModel::onLikeClicked,
            viewModel::onShareClicked,
            templateNoSuf,
            templateOneDigSuf,
            templateTwoDigSuf,
            suffixThousands,
            suffixMillions
        )`
